### ISSUE TITLE
code cell lines not wrapped

### ISSUE THREAD

**Issue by parthi2929** [t-makaro/nb_pdf_template#11]
Hi

I tried using classic.tplx for my nbconvert, but facing below issue. 

I tried wrapping by passing wrap_text(charlim) to input block also in style jupyter, but the resulting code is not wrapped at all. Here is a sample output (screenshot from pdf). 

![image](https://user-images.githubusercontent.com/11896263/44721667-49acdc00-aae8-11e8-91c2-dd95bbcb457b.png)

**Comment by t-makaro** [comment]
Ya, this is a notoriously difficult problem to solve. Default nbconvert templates have this same issue (except worse as the max length length varies). For outputs, we can just wrap the text, but for inputs, the highlighting makes the text longer so you can't predict at what length the text needs to wrap. We could wrap the text before highlighting is done, but then it might not highlight properly. I experimented with using the latex listings package, but that also didn't work with highlighting. 

For now, all I can recommend is keeping your lines to a max length of 86 characters for classic.tplx and 94 characters for classicm.tplx. Due to monospacing this will not overflow, and PEP8 recommends 80 characters anyway.

**Comment by t-makaro** [comment]
I may have figured out a solution to this problem. It involves using the latex package ```minted``` to highlight code. Unfortunately, since nbconvert does not use minted, I can not make it the default. This is because ```minted``` requires the use of a shell escape in order to compile to a pdf. 

I may be able to offer this as an option for those who are willing to modify their ```Jupyter_nbconvert_config.py``` file to use a shell escape in the latex command.

**Comment by t-makaro** [comment]
Fixed in version 2.0, but not by default. Please read the additional setup instructions in the readme.
